name: Drinking Disasters Card Game
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34256
title: Drinking Disasters Card Game
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b2a49'
    - '#ffffff'
    - '#fddd00'
    - '#00a1e1'
    - '#d12b2f'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
